49: move to position from analysis
DiamondLightSource/python-artemis pull request #112
Opened 2022-05-26 12:08 UTC by DominicOram

Fixes #49

Note: branched from https://github.com/DiamondLightSource/python-artemis/pull/110 so merge that first

2022-05-31 10:36 UTC, bentom08 commented
I noticed the grid position -> motor position method we have doesn't account for omega at all, is that already taken care of by epics/analysis or should we be adjusting the motor positions depending on our scan's omega angle? (as an example, we'll get different centring results taking scans at omega=0-90 vs omega=90-180 as the y/z axes will be flipped, but we should find the same x, y, z motor positions in each case)

2022-06-24 15:43 UTC, DominicOram commented
I think I do need to think about Ben's comment here. I will need to:
* Ensure the grid scan is done from omega = 0
* Move to omega = 0 before moving the other axes

2022-06-28 09:51 UTC, bentom08 requested changes
Needs to be rebased on main after which run_gridscan test will break and need updating

2022-06-28 09:51 UTC, bentom08 commented on src/artemis/fast_grid_scan_plan.py
> +    )
Must - Since #141 just got merged the test for this method will also need to be updated to mock this section

2022-06-28 09:51 UTC, bentom08 commented on src/artemis/tests/test_zocalo_interaction.py
> +    step_params = {"dcid": "8183741", "dcgid": "7263143"}
should - the values here which are also used further below (dcid and max_voxel) should be put into constants

2022-06-28 15:17 UTC, DominicOram commented
After discussing with @ndg63276 and @npat113 it's ok to assume `omega = 0` for now. We will fix this in https://github.com/DiamondLightSource/python-artemis/issues/154

2022-07-15 10:34 UTC, DominicOram commented
As seen on beamline the assert for the omega needs to be less severe and just check that they are close

2022-07-25 12:03 UTC, bentom08 approved these changes
Looks good

2022-07-29 11:06 UTC, merged