Store 2 sets of snapshots for 3d scans
DiamondLightSource/python-artemis pull request #142
Opened 2022-06-23 14:43 UTC by bentom08

Fixes #134

To Test -

Artemis side should just need unit tests to pass, GDA side of this issue will need beamline testing

2022-06-23 14:52 UTC, DominicOram commented
See https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/35058/11..12 for GDA side

2022-06-24 14:24 UTC, bentom08 commented
https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/35058/11..13 new GDA patchset for this change

2022-06-27 15:18 UTC, DominicOram requested changes
Looks good generally, need to fix the issue in GDA

2022-06-27 15:18 UTC, DominicOram commented on src/artemis/ispyb/ispyb_dataclass.py
> +    xtal_snapshots_z: List[str]
**nit**: It's only y/z 'cos we're assuming 0/90. Maybe better to do something like omega start and omega end?

2022-06-28 13:52 UTC, DominicOram approved these changes
Great, thank you!

2022-06-28 14:21 UTC, merged