88 fix nonetype errors from dataclasses json
DiamondLightSource/python-artemis pull request #279
Opened 2022-10-18 10:34 UTC by evalott100

2022-10-21 16:25 UTC, DominicOram commented on src/artemis/devices/eiger.py
> +        self.cam.acquire.set(1).wait(timeout=10)
Good catch!

2022-10-22 12:29 UTC, DominicOram requested changes
Thanks to looking into this, it does remove the warnings. However, couple of bits:
* I don't think we should be setting these params to optional, in production they are always required to be set and having them optional implies that's not the case
* You have some code in here for the issue around swapping `image_size`, can you remove it from here and make sure it's just on the correct branch

2022-10-24 08:44 UTC, evalott100 commented
> I don't think we should be setting these params to optional, in production they are always required to be set and having them optional implies that's not the case

I agree, I think it was a quirk of the typing. I'll rewrite it to make it non-optional.

> You have some code in here for the issue around swapping image_size, can you remove it from here and make sure it's just on the correct branch

My bad, I'll start double checking this

2022-10-27 16:21 UTC, DominicOram approved these changes
Thanks, this reduces the warning significantly.

2022-10-27 16:21 UTC, merged