#239 made sure there wasn't an inversion, wrote a unit test to check …
DiamondLightSource/python-artemis pull request #280
Opened 2022-10-18 10:36 UTC by evalott100

…constants set appropriately to the NexusWriter

2022-10-22 12:53 UTC, DominicOram requested changes
Looks good to me, minor comment in code, otherwise good, thanks!

2022-10-22 12:53 UTC, DominicOram commented on src/artemis/nexus_writing/write_nexus.py
> +        "image_size": [detector_pixels.height, detector_pixels.width],  # (fast, slow)
Should: This comment is now wrong, it should be  `# (slow, fast)` to match the `fast_axis`, `slow_axis` above.

2022-10-24 10:33 UTC, evalott100 reviewed
Changes made

2022-10-24 10:34 UTC, DominicOram approved these changes
Great, thanks!

2022-10-24 10:35 UTC, merged