Put the FastGridScan device in I03Smargon.
DiamondLightSource/python-artemis pull request #283
Opened 2022-10-20 13:19 UTC by evalott100

We should rethink where the I03Smargon class should go - using it in motors.py is problematic as the is_valid function in fast_grid_scan.py uses the XYZLimitBundle class as a type for the limits it imports, which can't be imported from motors.py without a circular import error. #155

2022-10-27 16:06 UTC, DominicOram requested changes
Looks good, I think we can solve the circular import by just putting the smargon in it's own file.

2022-11-18 11:29 UTC, DominicOram commented
Once https://github.com/DiamondLightSource/python-artemis/pull/371 is merged this will be a bit easier

2022-12-16 09:52 UTC, evalott100 commented
@DominicOram I don't know if it's as simple as the above commit. Do I need to change references to fast grid scan? Would be good to talk about.

2022-12-16 10:09 UTC, closed without merging

2022-12-16 10:13 UTC, evalott100 commented
Closing due to the branch being too out of date with main. The new pull request is #455