164 use documents for processing
DiamondLightSource/python-artemis pull request #292
Opened 2022-10-21 11:00 UTC by dperl-dls

2022-10-28 10:26 UTC, DominicOram requested changes
Great refactor, thank you! I think to avoid `main` having in progress work on it we should remove the parts that hint at ispyb/zocalo in this PR and just have them in https://github.com/DiamondLightSource/python-artemis/pull/295, comments reflect this. 

I'm also a bit torn about the `testing_plan`. While we can't run the full thing in dev easily I see why it's useful but I don't think it will ever be that useful in production so I'm not keen on adding it into `__main__.py`. Instead I think it should just have it's own `__main__` in the same file that we can use to run it. e.g. like the `snapshot_plan`

2022-10-28 10:26 UTC, DominicOram commented on src/artemis/fgs_communicator.py
> +        self.params = parameters
Nit: technically we don't need to store the params as we only use them here.

2022-10-28 10:26 UTC, DominicOram commented on src/artemis/tests/test_fgs_communicator.py
> +
Should: These tests are a great start, thank you! I think there's a few more we can add to make it more comprehensive though:
* We can patch out the communicator nexus writers by doing `@patch("fgs_communicator.NexusWriter` and assert that correct things are done on start/stop (we should probably do this even if we don't do the asserts as currently it means the tests are doing actual file writing)
* I think a test where we have a dummy plan that just starts/stops a run then having the FGSCommunicator subscribed to a RE that runs the plan and asserting that the nexus writer mocks are called correctly would be great. This is a bit more than a unit test I guess but proves the whole stack works
* A test that when the nexus writing throws an exception the RE doesn't continue and is in an error state that we can read out to send to GDA. (I know this is more functionality of Bluesky itself but by adding an explicit test for it you're saying it's important functionality that we have thought about)

2022-10-28 10:26 UTC, DominicOram commented on src/artemis/tests/test_main_system.py
> +    def subscribe(self, *args: Any):
Should: Can you add a test somehwere in this file that an FGSCommunicator gets passed into this at some point

2022-10-31 10:00 UTC, dperl-dls commented
closed in favour of #295

2022-10-31 10:00 UTC, closed without merging