367 experiment registry
DiamondLightSource/python-artemis pull request #384
Opened 2022-11-22 13:34 UTC by dperl-dls

Fixes #367 

Looks up the experiment plan from a "registry" which can later be made more dynamic

### To test:
1. Consider if this is a good way to approach this?
2. Run tests

2022-11-22 13:57 UTC, DominicOram commented
@callumforrester and @abbiemery this will basically be replaced by `blueapi` soon, is there any way we should change this to make that move easier?

2022-11-22 14:08 UTC, callumforrester commented
@DominicOram Probably not, current thinking for blueapi is to have a module full of plans and build the registry automagically from that.

2022-12-02 14:02 UTC, DominicOram reviewed
I think the registry idea is reasonably sensible and this will work. However, I think we could refactor around the stop a bit. Currently you need to put to `/plan/stop`, but when we move to multiple plans we probably don't want to have to keep track of which plans are running and so would be good to just be able to put to a top level `stop` endpoint. Status is also maybe a thing that you might want universal too, like a `/status` endpoint you can read from.

2022-12-02 14:16 UTC, dperl-dls commented on src/artemis/__main__.py
> +    experiment: str
yeah makes sense, will do that as well as for stop/status as mentioned in your comment

2023-01-23 17:31 UTC, DominicOram requested changes
If I send a bad request it's not obvious why it failed e.g.
```
(.venv) [ffv81422@ws455 python-artemis]$ curl -X PUT http://127.0.0.1:5005/bad_plan/start --data-binary "@test_parameters.json" -H "Content-Type: application/json"
{
    "status": "Success",
    "message": ""
}
(.venv) [ffv81422@ws455 python-artemis]$ curl http://127.0.0.1:5005/status
{
    "status": "Failed",
    "message": ""
}
```
I think it would be better if the `PUT` returned a `Failed` status if the plan doesn't exist? Could we have test covering this too?

2023-01-24 14:49 UTC, DominicOram approved these changes
Great, thank you very much!

2023-01-24 14:50 UTC, merged