391 ispyb interaction and comment
DiamondLightSource/python-artemis pull request #405
Opened 2022-11-28 17:33 UTC by dperl-dls

Fixes #391 #393 
Includes changes from #400
Loads existing comment from ispyb and appends if there was an error

### To test:
1. Run tests
2. Ideally, run a grid scan with S03, and the dev ispyb config in the $ISPYB_CONFIG_PATH env variable, inspect the logs and see that the comment is loaded

2022-11-29 18:02 UTC, DominicOram requested changes
Looks good, nice and neat
* I'm not sure if we should keep `TESTING_smargon` in? If we do can you add a comment on https://github.com/DiamondLightSource/python-artemis/issues/377 to remove it?
* The sqlalchemy interface to ispyb is nice, can you make an issue to look into using it for writing?
* I added a system test for the ispyb interaction, can you review it for me

2022-11-30 10:08 UTC, dperl-dls commented on src/artemis/external_interaction/communicator_callbacks.py
> +        ispyb_config = os.environ.get("ISPYB_CONFIG_PATH", SIM_ISPYB_CONFIG)
done

2022-11-30 11:30 UTC, dperl-dls commented on src/artemis/external_interaction/ispyb/store_in_ispyb.py
> +        with ispyb.open(self.ISPYB_CONFIG_FILE) as self.conn:
nope, dunno how that snuck in there

2022-11-30 11:31 UTC, dperl-dls commented on src/artemis/external_interaction/ispyb/store_in_ispyb.py
> +    def get_current_datacollection_comment(self, dcid: int) -> str:
yep

2022-11-30 12:14 UTC, dperl-dls commented
I would like to keep the TESTING_I03Smargon device for now, I tend to do a lot of testing with S03 and it might take a while before we have added the PVs. Made a note to remove it.

2022-11-30 13:15 UTC, dperl-dls commented on src/artemis/external_interaction/ispyb/store_in_ispyb.py
> +            current_comment = ""
- Added case of nothing coming back to the system test
- Logging and swallowing exceptions in `get_current_datacollection_comment`
- Added a unit test for this

2022-12-02 13:44 UTC, DominicOram approved these changes
Great, thank you!

2022-12-02 13:44 UTC, merged