Calculations and run plan for OAV loop  centring
DiamondLightSource/python-artemis pull request #456
Opened 2022-12-16 14:51 UTC by evalott100

Fixes #420 
Replaces #453, since that branch contained other changes.
To test:
* Run against s03 and the branch of issue 26 in 
* Check output is acceptable.

2022-12-20 12:20 UTC, DominicOram requested changes
This is a review from readability more than correctness, will test correctness more after lunch. As discussed I think that we should label the co-ordinate system coming out of the OAV as i, j, k and be explicit somewhere how that is defined relative to x, y, z.

Should: Do we have the plan we tested on the beamline that moves to tip centre? We should recover it and put it in a PR

Should: I think coming up with some better datastructures would be good, rather than just numpy arrays everywhere. I'll write an issue for this

2022-12-21 11:29 UTC, evalott100 commented on src/artemis/devices/oav/oav_calculations.py
> +        return
You're right it's an unnecessary check, an oversight from before I split into smaller methods.

2023-02-13 16:07 UTC, DominicOram requested changes
This isn't going to work in it's current state and it needs further testing on the beamline

2023-02-21 14:57 UTC, DominicOram approved these changes
This was successfully tested on the beamline and so I'm happy to merge it

2023-02-21 14:57 UTC, merged