554 tidy oav
DiamondLightSource/python-artemis pull request #584
Opened 2023-03-16 09:26 UTC by dperl-dls

Fixes #554 

Link to dodal PR (if required): [#25](https://github.com/DiamondLightSource/dodal/pull/25)

### To test:
1. Check organisation/naming of oav code is sensible/coherent
2. Run tests with both artemis and dodal branches

2023-03-27 14:36 UTC, DominicOram requested changes
Thanks for making a start on this but I think it still needs more cleaning up from prototyping. I think to merge it we need at least a unit test against some fake devices to confirm the plan runs through. Can you also address all the `must`s.

Can you write up issues for the other comments if you don't address them here? I also think this doesn't address all of the things on the issue it links. I have ticked the ones I think it fixes, can you split the others out into new issues?

2023-03-27 14:36 UTC, DominicOram commented on src/artemis/experiment_plans/full_grid_scan.py
> +    display_config = "/dls_sw/i03/software/gda_versions/var/display.configuration"
Should: These hardcoded paths need removing, they should come in as params

2023-03-27 14:36 UTC, DominicOram commented on src/artemis/experiment_plans/oav_grid_detection_plan.py
> +    # )
Should: Remove commented out code

2023-03-27 14:36 UTC, DominicOram commented on src/artemis/experiment_plans/full_grid_scan.py
> +    raise Exception("Detector not finished moving")
Should: This is much like the waiting for fast grid scan to be valid, e.g. messy and horrible. I think we need to put it in the device side probably? Certainly refactor it to be more Bluesky idiomatic

2023-03-27 14:51 UTC, DominicOram commented on src/artemis/utils/oav_utils.py
> +    on a size of (1024, 768) so we require these scaling factors.
Should: This comment is not correct in that we don't use the scaling factors

2023-03-27 15:32 UTC, dperl-dls commented on src/artemis/device_setup_plans/setup_oav.py
> +    yield from bps.abs_set(oav.snapshot.input_pv, parameters.input_plugin + ".CAM")
renamed all of them to input_plugin

2023-03-30 09:31 UTC, dperl-dls commented
Fair enough, in that case, I'd like to get 561_558 merged first, since changes there will affect the work that needs to be done here quite a lot

2023-05-11 16:04 UTC, DominicOram requested changes
Looks good, thanks. I tried to spin out as much as possible into other issues, what's left is things we can hopefully quickly fix now

2023-05-11 16:04 UTC, DominicOram commented on src/artemis/experiment_plans/oav_grid_detection_plan.py
> +            filenames["snap_1_filename"] if angle == 0 else filenames["snap_2_filename"]
Will be addressed in https://github.com/DiamondLightSource/python-artemis/issues/651

2023-05-12 11:01 UTC, DominicOram commented on src/artemis/experiment_plans/full_grid_scan.py
> +    oav_params = OAVParameters("loopCentring", **oav_param_files)
Should: I think there is an issue using `loopCentring` here, spun out into https://github.com/DiamondLightSource/python-artemis/issues/653

2023-05-12 11:01 UTC, DominicOram approved these changes
Great, thanks for the additional tests

2023-05-12 11:02 UTC, merged