598 parameter processing
DiamondLightSource/python-artemis pull request #601
Opened 2023-04-03 11:58 UTC by dperl-dls

Fixes #598 
Requires GDA changes to params
Removes most of external_parameters classes and implements flexible transformation from external parameters to specific internal parameter classes for each plan

### To test:
1. Run tests

2023-04-18 16:45 UTC, DominicOram requested changes
Great, thank you. Minor comments and could you fix linting/tests

2023-04-19 07:31 UTC, dperl-dls commented on src/artemis/parameters/external_parameters.py
> +    # TODO improve failed validation error messages
It is removed in that pr already, but I'm removing it here too because `external_parameters` might have changed too much to be recognisable

2023-04-19 07:38 UTC, dperl-dls commented on src/artemis/parameters/internal_parameters/internal_parameters.py
> +        }
yeah, good idea

2023-04-19 07:51 UTC, dperl-dls commented on src/artemis/parameters/internal_parameters/internal_parameters.py
> +        param_dict["position"] = Point3D(*param_dict["position"])
I think so, in case we ever initialise it independently. Anyway, this is going to be removed almost immediately.

2023-04-19 12:44 UTC, DominicOram approved these changes
Looks good, assuming you fix the merge conflicts. Thanks

2023-04-19 13:37 UTC, merged