Tidy up run artemis - Removed deployment, improved help, tidier arguments
DiamondLightSource/python-artemis pull request #611
Opened 2023-04-13 10:56 UTC by olliesilvester

Fixes #603

### To test:
1. Confirm running ./run_artemis.sh --help combines help from the start-up script and artemis
2. Check other arguments still work as usual
3. Check other cleanup changes are suitable

2023-04-14 09:25 UTC, dperl-dls requested changes
It seems like dev mode is not added to the options in `run_artemis.sh`, when I try `./run_artemis.sh --dev` I get `Unknown option --dev. Use --help for info on option usage.` Also, deploy should be removed from the help menu if the command is removed.

2023-04-17 15:40 UTC, dperl-dls requested changes
the `--verbose-event-logging` option also doesn't work - it's not in the start script and therefore not passed on to artemis

2023-04-18 14:01 UTC, olliesilvester commented
> the `--verbose-event-logging` option also doesn't work - it's not in the start script and therefore not passed on to artemis

Thanks, --logging-level was also missing. Hopefully these are fine now

2023-04-18 14:42 UTC, dperl-dls commented on run_artemis.sh
> +    echo "Invalid logging level selected, defaulting to INFO"
nice

2023-04-18 17:32 UTC, merged