526 do rotation scans
DiamondLightSource/python-artemis pull request #621
Opened 2023-04-20 07:59 UTC by dperl-dls

Fixes #526 
Implements a rotation_scan_plan and a few small support things necessary for it:
- reworks callback collections a bit
- 

### To test:
1. Run tests including system tests
2. Test on beamline

2023-05-11 09:49 UTC, DominicOram commented
Review and comment on glaring things only, new issues created for smaller things

2023-05-17 12:45 UTC, DominicOram requested changes
Good start, some comments in code. I think it would have been a little cleaner to not have done any Nexus Callback stuff in this PR as we'll now end up with placeholder/half finished stuff on main but there's no point being a purist and removing it now. Given the `rotation_scan_plan` is a bit more scientist facing it would be good for it to have some docstrings. I think for the major stuff I've put it in new issues. Feel free to make other new issues for things (apart from the `must` comment).

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +def move_to_start_w_buffer(motors: Smargon, start_angle):
Nit: What does `w_buffer` here mean? It's not a very clear term

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.abs_set(motors.omega.velocity, 120, wait=True)
Must: Actually it's overwriting below where it is set based on exposure time, is this a mistake?

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +        # TODO planify these
Should: Make an issue for this rather than a TODO

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +        eiger.set_num_triggers_and_captures()
Should: Why are we calling this function here? It's done as part of `stage`

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
> +            # with patch.object(RE, "_read", MagicMock(return_value=0)):
Should: Remove commented out code

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
> +    assert mock_omega_sets.call_count == 4
Should: This seems like an arbitrary assertion. Maybe better to assert the values are as expected

2023-05-17 12:45 UTC, DominicOram commented on src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
> +def test_cleanup_happens(
Nit: I would split this into two tests, one with the failure and one without. Probably also add a third that confirms it cleans up when no error happens

2023-05-22 12:45 UTC, dperl-dls commented on .vscode/launch.json
>              },
It's just the default for anyone

2023-05-22 13:24 UTC, dperl-dls commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.abs_set(motors.omega.velocity, 120, wait=True)
no, it's just the velocity for moving to the start should be fast, I'll add a comment

2023-05-22 13:32 UTC, dperl-dls commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.wait("cleanup_senv")
can't do this because generators
https://peps.python.org/pep-0255/#specification-yield
but I agree it's ugly, will make an issue to clean this up

2023-05-22 15:00 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.abs_set(motors.omega.velocity, 120, wait=True)
We could do something like `FAST_MOVE_TO_START=120`, bit more self-documenting

2023-05-22 15:05 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.wait("cleanup_senv")
:( can we use the `finalize_wrapper` in Bluesky?

2023-05-22 15:16 UTC, dperl-dls commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.wait("cleanup_senv")
ah yeah of course, much better

2023-05-26 12:37 UTC, DominicOram commented on src/artemis/experiment_plans/rotation_scan_plan.py
> +    yield from bps.abs_set(axis.velocity, 120, wait=True)
Nit: See https://github.com/DiamondLightSource/python-artemis/issues/685

2023-05-26 12:42 UTC, DominicOram approved these changes
Great, thank you!

2023-05-26 12:45 UTC, merged