I23 grid scans
DiamondLightSource/python-artemis pull request #663
Opened 2023-05-17 14:04 UTC by NeilSmithDLS

Fixes #578 and #574

Link to dodal PR (if required): #59 (https://github.com/DiamondLightSource/dodal/pull/59)

This change introduces the stepped_grid_scan end point and the associated changes required to perform the basic movement required for a stepped grid scan.

### To test:
1. Ensure https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/38922 is installed into GDA.
2. Run GDA for i23
3. Press the "Xray Centring" button on the OAV controls area
4. Within Hyperion confirm that the stepped grid scan plan is called and the x & y motors are moved

2023-05-17 14:05 UTC, NeilSmithDLS commented on gridscan_playing.py
This file si not needed and should be deleted from the Pull Request

2023-05-17 14:08 UTC, NeilSmithDLS commented on src/artemis/experiment_plans/stepped_grid_scan_plan.py
> +    LOGGER.info("******* get_plan called")
This line should be removed

2023-05-17 14:43 UTC, NeilSmithDLS commented on gridscan_playing.py
file removed

2023-05-17 14:43 UTC, NeilSmithDLS commented on src/artemis/experiment_plans/stepped_grid_scan_plan.py
> +    LOGGER.info("******* get_plan called")
done

2023-05-17 14:43 UTC, NeilSmithDLS commented on src/artemis/device_setup_plans/setup_zebra_for_stepped_grid_scan.py
file removed

2023-05-17 15:56 UTC, DominicOram requested changes
Really good basis to start from, thank you! Some minor comments in code of places we can remove a bit more that was copied over

2023-05-17 15:56 UTC, DominicOram commented on src/artemis/experiment_plans/stepped_grid_scan_plan.py
> +    )
Should: Maybe a new issue but this is an exact copy of the `fast_grid_scan` one, it should probably be somewhere common

2023-08-07 10:57 UTC, DominicOram commented
Sorry, just realised this is on me. Will  review now

2023-08-07 11:04 UTC, DominicOram approved these changes
Great, thank you!

2023-08-21 09:13 UTC, merged