Created a more generic callback structure to more easily allow different plans
DiamondLightSource/python-artemis pull request #669
Opened 2023-05-19 10:02 UTC by DominicOram

Fixes #668

### To test:
1. Confirm tests pass, including new test
2. Confirm this is compatible with the work done in https://github.com/DiamondLightSource/python-artemis/pull/621

2023-05-19 12:46 UTC, olliesilvester commented on src/artemis/experiment_plans/experiment_registry.py
>          "setup": do_nothing,
Could add `"callback_collection_type": NullPlanCallbackCollection` here as we discussed

2023-05-19 14:35 UTC, olliesilvester requested changes
All good other than the one comment I left

2023-05-22 09:49 UTC, dperl-dls approved these changes

2023-05-22 09:53 UTC, olliesilvester approved these changes

2023-05-22 10:03 UTC, merged