Tests for full grid scan
DiamondLightSource/python-artemis pull request #730
Opened 2023-06-13 13:58 UTC by Tom-Willemsen

Fixes https://github.com/DiamondLightSource/python-artemis/issues/674

Adds a unit test for `full_grid_scan`

Note: depends on https://github.com/DiamondLightSource/python-artemis/pull/722

2023-06-13 15:05 UTC, DominicOram requested changes
Generally good, minor tidying up I think you could do. Also some minor workflow issues:
* We usually to add the issue number in the branch name and commit messages e.g. see https://github.com/DiamondLightSource/python-artemis/pull/708. People are a bit hit and miss about it though, not a big deal.
* vscode should be sorting imports on save, do you have the following in your `settings.json`?
```
"editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "python.sortImports.args": [
        "--profile",
        "black"
    ],
```

2023-06-13 15:05 UTC, DominicOram commented on src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
> +    test_config_files,
Could: A few type hints in here would be nice

2023-06-13 16:34 UTC, DominicOram approved these changes
Looks good, wait until #722 is merged but otherwise fine

2023-06-14 13:22 UTC, dperl-dls commented
merging as #722  is merged now

2023-06-14 13:22 UTC, merged