Use callbacks in grid detection plan
DiamondLightSource/python-artemis pull request #731
Opened 2023-06-13 14:19 UTC by noemifrisina

Fixes #671 

Link to dodal PR (if required): [#91](https://github.com/DiamondLightSource/dodal/pull/91)
(remember to update `setup.cfg` with the dodal commit tag if you need it for tests to pass!)

### To test:
1.Run tests

2023-06-13 16:24 UTC, DominicOram requested changes
Minor comments in code, I think we should also merge https://github.com/DiamondLightSource/python-artemis/pull/730 first so that we can ensure it doesn't break tests

2023-06-13 16:24 UTC, DominicOram commented on src/artemis/experiment_plans/full_grid_scan.py
>          yield from grid_detection_plan(
Should: I think you can do the subscribe/unsubscribe in a decorator

2023-06-13 16:24 UTC, DominicOram commented on src/artemis/experiment_plans/oav_grid_detection_plan.py
> +        yield from bps.create("snapshot_directories")
Should: This isn't just directories any more

2023-06-14 11:56 UTC, noemifrisina commented
Done, thanks

2023-06-15 12:30 UTC, DominicOram commented
Could you:
* Fix conflicts
* Confirm test in https://github.com/DiamondLightSource/python-artemis/pull/730 still works on this
* Add new tests if you think that https://github.com/DiamondLightSource/python-artemis/pull/730 doesn't fully test the functionality

2023-06-16 16:26 UTC, DominicOram approved these changes
Looks good, thanks

2023-06-16 16:26 UTC, merged